---
- name: Set default backup path
  ansible.builtin.set_fact:
    network_restore_backup_path: "./tmp_backup"
  when: data_store.local is not defined

- name: Set default host vars path
  ansible.builtin.set_fact:
    network_restore_backup_path: "{{ data_store['local'] }}"
  when: data_store['local'] is defined

- name: Retrieve a repository from a distant location and make it available locally
  ansible.builtin.include_tasks: includes/retrieve.yaml
  when: data_store.scm is defined

- name: Include tasks
  ansible.builtin.include_tasks: includes/network.yaml
