---
- name: Retrieve the host vars with token access (if provided)
  ansible.scm.git_retrieve:
    origin:
      url: "{{ data_store['scm']['origin']['url'] }}"
      token: "{{ data_store['scm']['origin']['token'] | d(None) }}"
    parent_directory: "{{ role_path }}/{{ network_restore_backup_path }}"
  changed_when: false
  register: resource_manager_result

- name: Update Inventory Path
  ansible.builtin.set_fact:
    network_restore_backup_repo: "{{ resource_manager_result['path'] }}"

- name: Update Inventory Path
  ansible.builtin.set_fact:
    network_restore_backup_path: "{{ resource_manager_result['path'] }}/{{ data_store['scm']['origin']['path'] }}"
