---
authors:
  - Rohit Thakur (rohitthakur2590)
dependencies:
  "ansible.netcommon": ">=5.1.1"
  "ansible.utils": ">=2.9.0"
license_file: LICENSE
name: backup
description: Ansible Network Backup collection platform-agnostic single entry point management for network backup.
namespace: network
readme: README.md
repository: https://github.com/ansible-network/network.backup
issues: https://github.com/ansible-network/network.backup/issues
tags: [networking]
version: 0.0.1
