---
- name: Configurable backup path
  ansible.netcommon.cli_backup:
    dir_path: "{{ network_backup_path }}"
    filename:  "{{ data_store.backup_file_name | default(inventory_hostname) }}.txt"

  register: network_backup
