---
- name: Include tasks
  ansible.builtin.include_tasks: validation.yaml

- name: Run the platform specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ operation }}.yaml"
    - "unsupported_operation.yaml"
