---
- name: Include tasks
  ansible.builtin.include_tasks: includes/validation.yaml

- name: Run the platform specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "includes/{{ operation }}.yaml"
    - "includes/unsupported_operation.yaml"
